### PR TITLE
[WIP] Fix lazy stack / stack_onto

### PR DESCRIPTION
**Pull request by vmoens**

### CODE REVIEW

**Comment by matteobettini** [comment]
Here is a test for it
```python
class TestNestedLazyStacks:
    def get_agent_tensors(
        self,
        i,
    ):
        camera = torch.zeros(32, 32, 3)
        vector_3d = torch.zeros(3)
        vector_2d = torch.zeros(2)
        lidar = torch.zeros(20)

        agent_0_obs = torch.zeros(1)
        agent_1_obs = torch.zeros(1, 2)
        agent_2_obs = torch.zeros(1, 2, 3)

        # Agents all have the same camera
        # All have vector entry but different shapes
        # First 2 have lidar and last sonar
        # All have a different key agent_i_obs with different n_dims
        if i == 0:
            return TensorDict(
                {
                    "camera": camera,
                    "lidar": lidar,
                    "vector": vector_3d,
                    "agent_0_obs": agent_0_obs,
                },
                [],
            )
        elif i == 1:
            return TensorDict(
                {
                    "camera": camera,
                    "lidar": lidar,
                    "vector": vector_2d,
                    "agent_1_obs": agent_1_obs,
                },
                [],
            )
        elif i == 2:
            return TensorDict(
                {
                    "camera": camera,
                    "vector": vector_2d,
                    "agent_2_obs": agent_2_obs,
                },
                [],
            )
        else:
            raise ValueError(f"Index {i} undefined for 3 agents")

    def get_lazy_stack(self, batch_size):
        agent_obs = []
        for angent_id in range(3):
            agent_obs.append(self.get_agent_tensors(angent_id))
        agent_obs = torch.stack(agent_obs, dim=0)
        obs = TensorDict(
            {
                "agents": agent_obs,
                "state": torch.zeros(
                    64,
                    64,
                    3,
                ),
            },
            [],
        )
        obs = obs.expand(batch_size)
        return obs

 
    def dense_stack_tds_v2(
        self, td_list: List[TensorDictBase], stack_dim: int
    ) -> TensorDictBase:
        shape = list(td_list[0].shape)
        shape.insert(stack_dim, len(td_list))

        out = td_list[0].unsqueeze(stack_dim).expand(shape).clone()

        return torch.stack(td_list, dim=stack_dim, out=out)

    @pytest.mark.parametrize("batch_size", [(), (32,), (1, 2)])
    def test(self, batch_size):
        obs = self.get_lazy_stack(batch_size)
        for stack_dim in range(len(batch_size) + 1):
            res = self.dense_stack_tds_v2(
                [obs, obs], stack_dim=stack_dim
            )  
```

**Comment by matteobettini** [comment]
If you replace `dense_stack_tds_v2 ` with
```
def dense_stack_tds_v1(td_list: List[TensorDictBase], stack_dim: int) -> TensorDictBase:
    shape = list(td_list[0].shape)
    shape.insert(stack_dim, len(td_list))

    out = td_list[0].unsqueeze(stack_dim).expand(shape).clone()
    for i in range(1, len(td_list)):
        index = (slice(None),) * stack_dim + (i,)  # this is index_select
        out[index] = td_list[i]

    return out
```

you can also see that the heterogenous shape bug comes up also in `__setitem__`

**Comment by vmoens** [comment]
On it I think i've found where the problem was
Nit for the tests:
- we should avoid domain-specific terms
- we should avoid looping over use cases in the test
- we should avoid batch size of 32 or similar, they quickly pile up to large tensors which is unnecessary

**Comment by matteobettini** [comment]
Few things that I found when trying to understand this:
- https://github.com/pytorch-labs/tensordict/blob/main/tensordict/tensordict.py#L3396 when `__setitem__` is called on a LazyStack with a LazyStack value, the lazy keys (and all their recursively hidden children) will be not considered
- at the same line, when value is a LazyStack and one entry is het, `items()` will crash while trying to get it

**Comment by vmoens** [comment]
> Few things that I found when trying to understand this:
> 
> * https://github.com/pytorch-labs/tensordict/blob/main/tensordict/tensordict.py#L3396 when `__setitem__` is called on a LazyStack with a LazyStack value, the lazy keys (and all their recursively hidden children) will be not considered
> * at the same line, when value is a LazyStack and one entry is het, `items()` will crash while trying to get it

this isn't related to stack(... out=smth) right?

**Comment by matteobettini** [comment]
but they might affect part of this downstream

**Comment by vmoens** [comment]
I don't think so (though i would not rule it out completely)
usually after you get through an entry point like `__setitem__` or similar you will only pass from private method to private method

**Comment by matteobettini** [comment]
> I don't think so (though i would not rule it out completely)
> usually after you get through an entry point like `__setitem__` or similar you will only pass from private method to private method

I think __setitem__ is used here https://github.com/pytorch-labs/tensordict/blob/main/tensordict/utils.py#L825 , called from here https://github.com/pytorch-labs/tensordict/blob/main/tensordict/tensordict.py#L4142 on Lazy stack

Here is a set of tests that I think will test some of interesting cases
```python
class TestNestedLazyStacks:
    @staticmethod
    def nested_lazy_het_td(batch_size):
        shared = torch.zeros(4, 4, 2)
        hetero_3d = torch.zeros(3)
        hetero_2d = torch.zeros(2)

        individual_0_tensor = torch.zeros(1)
        individual_1_tensor = torch.zeros(1, 2)
        individual_2_tensor = torch.zeros(1, 2, 3)

        individual_0_td = torch.zeros(1)
        individual_1_td = torch.zeros(1, 2)
        individual_2_td = torch.zeros(1, 2, 3)

        td_list = [
            TensorDict(
                {
                    "shared": shared,
                    "hetero": hetero_3d,
                    "individual_0_tensor": individual_0_tensor,
                },
                [],
            ),
            TensorDict(
                {
                    "shared": shared,
                    "hetero": hetero_3d,
                    "individual_1_tensor": individual_1_tensor,
                },
                [],
            ),
            TensorDict(
                {
                    "shared": shared,
                    "hetero": hetero_2d,
                    "individual_2_tensor": individual_2_tensor,
                },
                [],
            ),
        ]
        for i, td in enumerate(td_list):
            td[f"individual_{i}_td"] = td.clone()
            td[f"shared_td"] = td.clone()

        td_stack = torch.stack(td_list, dim=0)
        obs = TensorDict(
            {"lazy": td_stack, "dense": torch.zeros(3, 3, 2)},
            [],
        )
        obs = obs.expand(batch_size)
        return obs

    def recursively_check_key(self, td, value: int):
        if isinstance(td, LazyStackedTensorDict):
            for t in td.tensordicts:
                if not self.recursively_check_key(t, value):
                    return False
        elif isinstance(td, TensorDict):
            for i in td.values():
                if not self.recursively_check_key(i, value):
                    return False
        elif isinstance(td, torch.Tensor):
            return (td == value).all()
        else:
            return False

        return True

    def dense_stack_tds_v1(
        self, td_list: List[TensorDictBase], stack_dim: int
    ) -> TensorDictBase:
        shape = list(td_list[0].shape)
        shape.insert(stack_dim, len(td_list))

        out = td_list[0].unsqueeze(stack_dim).expand(shape).clone()
        for i in range(1, len(td_list)):
            index = (slice(None),) * stack_dim + (i,)  # this is index_select
            out[index] = td_list[i]

        return out

    def dense_stack_tds_v2(
        self, td_list: List[TensorDictBase], stack_dim: int
    ) -> TensorDictBase:
        shape = list(td_list[0].shape)
        shape.insert(stack_dim, len(td_list))

        out = td_list[0].unsqueeze(stack_dim).expand(shape).clone()

        return torch.stack(td_list, dim=stack_dim, out=out)

    @pytest.mark.parametrize("batch_size", [(), (2,), (1, 2)])
    @pytest.mark.parametrize("stack_dim", [0, 1, 2])
    def test(self, batch_size, stack_dim):
        obs = self.nested_lazy_het_td(batch_size)
        obs1 = obs.clone()
        obs1.apply_(lambda x: x + 1)

        if stack_dim > len(batch_size):
            return

        res1 = self.dense_stack_tds_v1([obs, obs1], stack_dim=stack_dim)
        res2 = self.dense_stack_tds_v2([obs, obs1], stack_dim=stack_dim)

        index = (slice(None),) * stack_dim + (0,)  # get the first in the stack
        assert self.recursively_check_key(res1[index], 0)  # check all 0
        assert self.recursively_check_key(res2[index], 0)  # check all 0
        index = (slice(None),) * stack_dim + (1,)  # get the second in the stack
        assert self.recursively_check_key(res1[index], 1)  # check all 1
        assert self.recursively_check_key(res2[index], 1)  # check all 1

```

- to test just the feature in this PR you can drop the res1 lines
- the res2 lines will test __setitem__

**Comment by vmoens** [comment]
Tests are passing now, and i'll fix this too

**Review by matteobettini — APPROVED** [review]
LGTM

Can you add this to the tests?
```python
     def all_eq(
        self,
        td: Union[TensorDictBase, torch.Tensor],
        other: Union[TensorDictBase, torch.Tensor],
    ):
        if td.__class__ != other.__class__:
            return False

        if td.shape != other.shape or td.device != other.device:
            return False

        if isinstance(td, LazyStackedTensorDict):
            if td.stack_dim != other.stack_dim:
                return False
            for t, o in zip(td.tensordicts, other.tensordicts):
                if not self.all_eq(t, o):
                    return False
        elif isinstance(td, TensorDictBase):
            td_keys = list(td.keys())
            other_keys = list(other.keys())
            if td_keys != other_keys:
                return False
            for k in td_keys:
                if not self.all_eq(td[k], other[k]):
                    return False
        elif isinstance(td, torch.Tensor):
            return torch.equal(td, other)
        else:
            raise AssertionError()

        return True

    @pytest.mark.parametrize("batch_size", [(), (2,), (1, 2)])
    @pytest.mark.parametrize("stack_dim", [0, 1, 2])
    def test_setitem_hetero(self, batch_size, stack_dim):
        obs = self.nested_lazy_het_td(batch_size)
        obs1 = obs.clone()
        obs1.apply_(lambda x: x + 1)

        if stack_dim > len(batch_size):
            return

        res1 = self.dense_stack_tds_v1([obs, obs1], stack_dim=stack_dim)
        res2 = self.dense_stack_tds_v2([obs, obs1], stack_dim=stack_dim)

        index = (slice(None),) * stack_dim + (0,)  # get the first in the stack
        assert self.recursively_check_key(res1[index], 0)  # check all 0
        assert self.recursively_check_key(res2[index], 0)  # check all 0
        index = (slice(None),) * stack_dim + (1,)  # get the second in the stack
        assert self.recursively_check_key(res1[index], 1)  # check all 1
        assert self.recursively_check_key(res2[index], 1)  # check all 1

        assert self.all_eq(res1, res2)
```
it is an extra consistency check

**Comment by vmoens** [comment]
I'd rather not add that all_eq method, what does it do that a simple eq does not do?

**Comment by matteobettini** [comment]
> The reason is that, if for each new test we add a helper we'll end up with tests that are hard to modify or with lots of legacy code when we remove a test for eample

oh yes ofc, a normal equal returns some lazy keys in canse there are though right? how do i check all lazy keys match?

**Review by matteobettini — APPROVED** [review]
LGTM

**Pull request merged**
